export const DUMMY_COMMUNITIES = [
    {
        id: 'c1',
        name: 'Mindful Living',
        logo_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=100&h=100&fit=crop',
        followers_count: 1240,
    },
    {
        id: 'c2',
        name: 'Yoga Beginners',
        logo_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=100&h=100&fit=crop',
        followers_count: 850,
    },
    {
        id: 'c3',
        name: 'Healthy Eats',
        logo_url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=100&h=100&fit=crop',
        followers_count: 3200,
    },
    {
        id: 'c4',
        name: 'Daily Meditation',
        logo_url: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?w=100&h=100&fit=crop',
        followers_count: 512,
    },
];

export const DUMMY_CHATS = [
    {
        id: 'ch1',
        community: DUMMY_COMMUNITIES[0],
        last_message: {
            message_text: "Don't forget the session today at 5 PM!",
            user: { name: 'Sarah M.' },
            created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
        },
        unread_count: 3,
    },
    {
        id: 'ch2',
        community: DUMMY_COMMUNITIES[1],
        last_message: {
            message_text: "What mat do you recommend?",
            user: { name: 'John D.' },
            created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        },
        unread_count: 0,
    },
    {
        id: 'ch3',
        community: DUMMY_COMMUNITIES[2],
        last_message: {
            message_text: "I tried the new recipe, it was amazing 🥗",
            user: { name: 'Elena' },
            created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        },
        unread_count: 1,
    },
];

export const DUMMY_POSTS = [
    {
        id: 'p1',
        user: {
            id: 'u1',
            name: 'Emma Watson',
            avatar_url: 'https://i.pravatar.cc/150?u=emma',
        },
        community: DUMMY_COMMUNITIES[0],
        title: 'Finding Peace in Chaos',
        content: "Today I took 10 minutes just to breathe. It's amazing how a small pause can completely shift your perspective. I highly recommend taking a step back when things get overwhelming.",
        images: [{ image_url: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800&fit=crop' }],
        likes_count: 142,
        comments_count: 24,
        views_count: 1050,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        user_has_liked: true,
    },
    {
        id: 'p2',
        user: {
            id: 'u2',
            name: 'Michael Chen',
            avatar_url: 'https://i.pravatar.cc/150?u=michael',
        },
        community: DUMMY_COMMUNITIES[1],
        title: 'Mastering the Crow Pose',
        content: "Finally held the crow pose for 10 seconds! Here's a quick tip: look forward, not down. Your body follows your gaze. Keep practicing!",
        images: [{ image_url: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800&fit=crop' }],
        likes_count: 89,
        comments_count: 12,
        views_count: 530,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        user_has_liked: false,
    },
    {
        id: 'p3',
        user: {
            id: 'u3',
            name: 'Jessica Parker',
            avatar_url: 'https://i.pravatar.cc/150?u=jess',
        },
        community: DUMMY_COMMUNITIES[2],
        title: 'Quick Morning Smoothie',
        content: "Blend 1 banana, a handful of spinach, 1/2 cup almond milk, and a scoop of protein powder. Perfect start to the day! 🥤",
        images: [],
        likes_count: 210,
        comments_count: 45,
        views_count: 2200,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        user_has_liked: false,
    },
    {
        id: 'p4',
        user: {
            id: 'u4',
            name: 'David Smith',
            avatar_url: 'https://i.pravatar.cc/150?u=david',
        },
        community: DUMMY_COMMUNITIES[3],
        title: 'Overcoming Morning Anxiety',
        content: "If you wake up anxious, try not to reach for your phone immediately. Spend the first 5 minutes doing deep belly breathing. It sets a totally different tone for the day.",
        images: [{ image_url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&fit=crop' }],
        likes_count: 340,
        comments_count: 56,
        views_count: 4100,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
        user_has_liked: true,
    },
    {
        id: 'p5',
        user: {
            id: 'u5',
            name: 'Alex Johnson',
            avatar_url: 'https://i.pravatar.cc/150?u=alex',
        },
        community: null,
        title: 'Just a thought',
        content: "Sometimes the most productive thing you can do is relax.",
        images: [],
        likes_count: 56,
        comments_count: 2,
        views_count: 300,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
        user_has_liked: false,
    },
    {
        id: 'p6',
        user: {
            id: 'u6',
            name: 'Sophia Lee',
            avatar_url: 'https://i.pravatar.cc/150?u=sophia',
        },
        community: DUMMY_COMMUNITIES[0],
        title: 'Nature Walk Benefits',
        content: "Did you know that just 20 minutes in nature can significantly lower stress hormone levels? Take a walk today!",
        images: [{ image_url: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&fit=crop' }],
        likes_count: 125,
        comments_count: 18,
        views_count: 890,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
        user_has_liked: true,
    },
    {
        id: 'p7',
        user: {
            id: 'u7',
            name: 'Chris Evans',
            avatar_url: 'https://i.pravatar.cc/150?u=chris',
        },
        community: DUMMY_COMMUNITIES[1],
        title: 'Stretching Routine',
        content: "Consistency is more important than intensity when it comes to flexibility. 10 minutes a day beats 1 hour once a week.",
        images: [],
        likes_count: 78,
        comments_count: 9,
        views_count: 650,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
        user_has_liked: false,
    },
    {
        id: 'p8',
        user: {
            id: 'u8',
            name: 'Mia Wong',
            avatar_url: 'https://i.pravatar.cc/150?u=mia',
        },
        community: DUMMY_COMMUNITIES[2],
        title: 'Meal Prep Sunday',
        content: "Prepared all my lunches for the week! Quinoa bowls with roasted veggies and lemon tahini dressing.",
        images: [{ image_url: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&fit=crop' }],
        likes_count: 450,
        comments_count: 82,
        views_count: 5200,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
        user_has_liked: true,
    },
    {
        id: 'p9',
        user: {
            id: 'u9',
            name: 'Ryan Gosling',
            avatar_url: 'https://i.pravatar.cc/150?u=ryan',
        },
        community: DUMMY_COMMUNITIES[3],
        title: 'Evening Routine',
        content: "No screens 1 hour before bed has changed my sleep quality entirely. Reading a physical book helps transition the mind.",
        images: [],
        likes_count: 215,
        comments_count: 33,
        views_count: 1800,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
        user_has_liked: false,
    },
    {
        id: 'p10',
        user: {
            id: 'u10',
            name: 'Lily Collins',
            avatar_url: 'https://i.pravatar.cc/150?u=lily',
        },
        community: DUMMY_COMMUNITIES[0],
        title: 'Gratitude Journaling',
        content: "Writing down 3 things I'm grateful for every night. It sounds cliché, but it shifts your focus from what you lack to what you have.",
        images: [{ image_url: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=800&fit=crop' }],
        likes_count: 310,
        comments_count: 41,
        views_count: 2900,
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 192).toISOString(),
        user_has_liked: true,
    }
];
